/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { VoiceRecording } from "./VoiceRecording";
import { VoiceRecordingCountArgs } from "./VoiceRecordingCountArgs";
import { VoiceRecordingFindManyArgs } from "./VoiceRecordingFindManyArgs";
import { VoiceRecordingFindUniqueArgs } from "./VoiceRecordingFindUniqueArgs";
import { CreateVoiceRecordingArgs } from "./CreateVoiceRecordingArgs";
import { UpdateVoiceRecordingArgs } from "./UpdateVoiceRecordingArgs";
import { DeleteVoiceRecordingArgs } from "./DeleteVoiceRecordingArgs";
import { User } from "../../user/base/User";
import { VoiceRecordingService } from "../voiceRecording.service";
@graphql.Resolver(() => VoiceRecording)
export class VoiceRecordingResolverBase {
  constructor(protected readonly service: VoiceRecordingService) {}

  async _voiceRecordingsMeta(
    @graphql.Args() args: VoiceRecordingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [VoiceRecording])
  async voiceRecordings(
    @graphql.Args() args: VoiceRecordingFindManyArgs
  ): Promise<VoiceRecording[]> {
    return this.service.voiceRecordings(args);
  }

  @graphql.Query(() => VoiceRecording, { nullable: true })
  async voiceRecording(
    @graphql.Args() args: VoiceRecordingFindUniqueArgs
  ): Promise<VoiceRecording | null> {
    const result = await this.service.voiceRecording(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => VoiceRecording)
  async createVoiceRecording(
    @graphql.Args() args: CreateVoiceRecordingArgs
  ): Promise<VoiceRecording> {
    return await this.service.createVoiceRecording({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => VoiceRecording)
  async updateVoiceRecording(
    @graphql.Args() args: UpdateVoiceRecordingArgs
  ): Promise<VoiceRecording | null> {
    try {
      return await this.service.updateVoiceRecording({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => VoiceRecording)
  async deleteVoiceRecording(
    @graphql.Args() args: DeleteVoiceRecordingArgs
  ): Promise<VoiceRecording | null> {
    try {
      return await this.service.deleteVoiceRecording(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(
    @graphql.Parent() parent: VoiceRecording
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
