/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SearchQueryUpdateManyWithoutUsersInput } from "./SearchQueryUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { VoiceRecordingUpdateManyWithoutUsersInput } from "./VoiceRecordingUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SearchQueryUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SearchQueryUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SearchQueryUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  searchQueries?: SearchQueryUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: () => VoiceRecordingUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => VoiceRecordingUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => VoiceRecordingUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  voiceRecordings?: VoiceRecordingUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
